### ISSUE TITLE
Reverse the chunked content array so that the first paragraph of the article is in the last object group.

### ISSUE THREAD

**Issue by smaida** [fostermadeco/culturalanth#1]
Consider using array_reverse on the $content array here:

https://github.com/fostermadeco/culturalanth/blob/95732982b5f7c5e852328e1faa1bad0df4a83001/culanthtransformers/CulAnthTransfomer.php#L175

**Comment by jkim01** [comment]
Note: reversing the array seems to have solved the issue.
